# Generated by Django 4.2 on 2024-08-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_story_contributions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='contributions_count',
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(default='children', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
